#!/usr/bin/env bash
#
# run_tests.sh -- build and run the whole tiny-gpu compute-path test suite.
#
# Must be run from the repo root: shared_mem.sv's $readmemb paths
# ("mems/*.mem") are relative to the simulator's working directory.
#
#   ./run_tests.sh            # everything
#   ./run_tests.sh test6      # only tests whose name matches
#
# Exits nonzero if any test fails, so CI can rely on the status code.

set -u
cd "$(dirname "$0")"

FILTER="${1:-}"
BUILD=".sim"
RTL_SRC="SystemVerilog"

RTL=(
    "$RTL_SRC/gpu_pkg.sv"
    "$RTL_SRC/library.sv"
    "$RTL_SRC/cpu.sv"
    "$RTL_SRC/pc.sv"
    "$RTL_SRC/decoder.sv"
    "$RTL_SRC/fetcher.sv"
    "$RTL_SRC/scheduler.sv"
    "$RTL_SRC/core.sv"
    "$RTL_SRC/shared_mem.sv"
    "$RTL_SRC/data_buffer.sv"
    "$RTL_SRC/display/display_ controller.sv"
    "$RTL_SRC/display/vga-hdmi.sv"
    "$RTL_SRC/display/tmdsEncoder.sv"
    "$RTL_SRC/gpu.sv"
)

# testbench top module -> source file
TESTS=(
    "test0:testbenches/test0.sv"
    "test1_alu_tb:testbenches/test1_alu_tb.sv"
    "test2_rtype_tb:testbenches/test2_rtype_tb.sv"
    "test3_mem_tb:testbenches/test3_mem_tb.sv"
    "test4_branch_tb:testbenches/test4_branch_tb.sv"
    "test5_jump_tb:testbenches/test5_jump_tb.sv"
    "test6_lanes_tb:testbenches/test6_lanes_tb.sv"
    "test7_kernel_tb:testbenches/test7_kernel_tb.sv"
    "test_decoder_tb:testbenches/test_decoder_tb.sv"
    "test_shared_mem_tb:testbenches/test_shared_mem_tb.sv"
    "test8_filter_tb:testbenches/test8_filter_tb.sv"
    "test9_scanout_tb:testbenches/test9_scanout_tb.sv"
    "test10_dbuf_tb:testbenches/test10_dbuf_tb.sv"
    "test11_circle_tb:testbenches/test11_circle_tb.sv"
    "test12_gpu_c_tb:testbenches/test12_gpu_c_tb.sv"
    "test13_dbuf_scanout_tb:testbenches/test13_dbuf_scanout_tb.sv"
    "test14_tmds_tb:testbenches/test14_tmds_tb.sv"
    "test15_filter_c_tb:testbenches/test15_filter_c_tb.sv"
    "test16_invert_c_tb:testbenches/test16_invert_c_tb.sv"
)

for tool in xvlog xelab xsim python3; do
    command -v "$tool" >/dev/null 2>&1 || { echo "error: '$tool' not on PATH"; exit 2; }
done

mkdir -p "$BUILD"

# ---------------------------------------------------------------------------
# 1. regenerate every generated input (assembled programs, data images,
#    decoder vectors) so a stale .mem can never make a test look green
# ---------------------------------------------------------------------------
echo "### generating test inputs"
python3 python_scripts/gen_test_data.py       > "$BUILD/gen.log" 2>&1 || { cat "$BUILD/gen.log"; exit 2; }
python3 python_scripts/gen_decoder_vectors.py >> "$BUILD/gen.log" 2>&1 || { cat "$BUILD/gen.log"; exit 2; }
# Demo source image: mems/source.png is checked in, but regenerate it if it has
# gone missing so the filter tests always have an input.
if [ ! -f mems/source.png ]; then
    python3 python_scripts/img_tool.py testpattern mems/source.png >> "$BUILD/gen.log" 2>&1
fi
python3 python_scripts/img_tool.py to-mem mems/source.png mems/img_source.mem >> "$BUILD/gen.log" 2>&1 \
    || { echo "IMAGE PACKING FAILED"; tail -5 "$BUILD/gen.log"; exit 2; }
# The same image in data_buffer.sv's layout (one element per pixel), plus the
# blank buffer that kernels rendering from scratch start with.
# Deliberately mems/dbuf_test*, NOT mems/dbuf_photo*: this runs on every test
# invocation, so anything it writes gets clobbered constantly. The demo photo
# lives under dbuf_photo_bank* and is generated by hand -- a shared name here
# silently overwrote a user's image between converting it and building the
# bitstream, which then displayed the test pattern with no sign anything was
# wrong (the build log still showed the right filenames being read).
python3 python_scripts/img_tool.py to-dbuf mems/source.png mems/dbuf_test.mem >> "$BUILD/gen.log" 2>&1 \
    || { echo "DBUF PACKING FAILED"; tail -5 "$BUILD/gen.log"; exit 2; }
python3 python_scripts/img_tool.py zeros-dbuf mems/dbuf_zeros.mem >> "$BUILD/gen.log" 2>&1 \
    || { echo "DBUF ZEROS FAILED"; tail -5 "$BUILD/gen.log"; exit 2; }

# NOTE: mems/gpu_c.mem is NOT generated here -- it comes from the C compiler in
# the separate Lab4 tree, so it is checked in as a build artifact. To regenerate
# after editing gpu.c:
#     cd <Lab4> && python3 python_scripts/toolchain/cli.py \
#         compile python_scripts/part_b/programs/gpu.c --target tinygpu -o /tmp/g.asm
#     python3 python_scripts/toolchain/cli.py asm /tmp/g.asm -o /tmp/g
#     cp /tmp/g.mem <here>/mems/gpu_c.mem
for s in tests/*.s; do
    name="$(basename "$s" .s)"
    if ! python3 python_scripts/rvasm.py "$s" "mems/$name.mem" >> "$BUILD/gen.log" 2>&1; then
        echo "ASSEMBLER FAILED on $s:"
        tail -5 "$BUILD/gen.log"
        exit 2
    fi
done
echo "    $(ls tests/*.s | wc -l) programs assembled, data images and decoder vectors written"

# ---------------------------------------------------------------------------
# 2. analyze RTL + all testbenches once into the shared work library
# ---------------------------------------------------------------------------
echo "### compiling"
TB_FILES=()
for entry in "${TESTS[@]}"; do TB_FILES+=("${entry#*:}"); done

if ! xvlog -sv -i testbenches -log "$BUILD/xvlog.log" \
        "${RTL[@]}" testbenches/tb_harness.sv "${TB_FILES[@]}" > /dev/null 2>&1; then
    echo "COMPILE FAILED:"
    grep -E "ERROR|error" "$BUILD/xvlog.log" | head -30
    exit 2
fi
echo "    ok"

# ---------------------------------------------------------------------------
# 3. elaborate and run each testbench
# ---------------------------------------------------------------------------
pass=0; fail=0; skipped=0
failed_names=()

for entry in "${TESTS[@]}"; do
    top="${entry%%:*}"
    if [ -n "$FILTER" ] && [[ "$top" != *"$FILTER"* ]]; then
        skipped=$((skipped + 1))
        continue
    fi

    printf '%-22s ' "$top"

    if ! xelab -timescale 1ns/1ps "$top" -s "${top}_snap" \
            -log "$BUILD/$top.elab.log" > /dev/null 2>&1; then
        echo "ELABORATION FAILED  (see $BUILD/$top.elab.log)"
        fail=$((fail + 1)); failed_names+=("$top"); continue
    fi

    xsim "${top}_snap" -runall -log "$BUILD/$top.sim.log" > "$BUILD/$top.out" 2>&1
    rc=$?

    # Two independent verdicts: the exit status ($fatal on failure) and the
    # printed summary. test0.sv predates the shared scaffolding and only
    # prints, so the grep is what covers it.
    if [ $rc -eq 0 ] && grep -q "^PASS" "$BUILD/$top.out" && ! grep -q "FAIL" "$BUILD/$top.out"; then
        summary=$(grep -m1 "^PASS" "$BUILD/$top.out")
        cycles=$(grep -m1 -oE "in [0-9]+ cycles|after [0-9]+ cycles" "$BUILD/$top.out")
        echo "PASS  ${summary#PASS: }  ${cycles:+[$cycles]}"
        pass=$((pass + 1))
    else
        echo "FAIL"
        grep -E "^  FAIL|^FAIL|Error|ERROR" "$BUILD/$top.out" | head -12 | sed 's/^/      /'
        echo "      full log: $BUILD/$top.out"
        fail=$((fail + 1)); failed_names+=("$top")
    fi
done

# Framebuffer dumps -> PNGs, so the rendered result is inspectable as an image.
for dump in filter_out scanout; do
    if [ -s "$BUILD/$dump.txt" ]; then
        python3 python_scripts/img_tool.py from-frame "$BUILD/$dump.txt" \
            "$BUILD/$dump.png" >> "$BUILD/gen.log" 2>&1 \
            && echo "    image: $BUILD/$dump.png"
    fi
done

echo
echo "=========================================================="
if [ $fail -eq 0 ]; then
    if [ $skipped -gt 0 ]; then
        echo "ALL TESTS PASSED  ($pass passed, $skipped filtered out)"
    else
        echo "ALL TESTS PASSED  ($pass passed)"
    fi
else
    echo "$fail FAILED, $pass passed"
    printf '  failed: %s\n' "${failed_names[@]}"
fi
echo "=========================================================="
[ $fail -eq 0 ]
