# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function main() ----
fn_main:
    addi sp, sp, -8
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 8          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    li   t0, 100
    push t0
    li   t0, 7
    push t0
    pop  t1
    pop  t0
    mv   a0, t0
    mv   a1, t1
    call __divmod            # t0 = lhs / rhs
    mv   t0, a0
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    li   t0, 100
    push t0
    li   t0, 7
    push t0
    pop  t1
    pop  t0
    mv   a0, t0
    mv   a1, t1
    call __divmod            # t0 = lhs %% rhs
    mv   t0, a1
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    li   t0, -100
    push t0
    li   t0, 7
    push t0
    pop  t1
    pop  t0
    mv   a0, t0
    mv   a1, t1
    call __divmod            # t0 = lhs / rhs
    mv   t0, a0
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    li   t0, -100
    push t0
    li   t0, 7
    push t0
    pop  t1
    pop  t0
    mv   a0, t0
    mv   a1, t1
    call __divmod            # t0 = lhs %% rhs
    mv   t0, a1
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    li   t0, 100
    push t0
    li   t0, 7
    push t0
    pop  t1
    pop  t0
    mv   a0, t0
    mv   a1, t1
    call __divmod            # t0 = lhs / rhs
    mv   t0, a0
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- runtime: unsigned divmod ----
__udivmod:
    mv   t0, a0              # t0 = dividend
    mv   t1, a1              # t1 = divisor
    bne  t1, zero, __udm_nz
    li   a0, -1
    mv   a1, t0
    ret
__udm_nz:
    li   t2, 0               # quotient
    li   t3, 0               # remainder
    li   t4, 31              # bit index
__udm_loop:
    slli t3, t3, 1
    srl  t5, t0, t4
    andi t5, t5, 1
    or   t3, t3, t5          # r = (r<<1) | bit i of dividend
    bltu t3, t1, __udm_skip
    sub  t3, t3, t1          # r -= divisor
    li   t5, 1
    sll  t5, t5, t4
    or   t2, t2, t5          # set bit i of quotient
__udm_skip:
    addi t4, t4, -1
    bgez t4, __udm_loop
    mv   a0, t2
    mv   a1, t3
    ret

# ---- runtime: signed divmod (C truncate-toward-zero) ----
__divmod:
    addi sp, sp, -12
    sw   ra, 8(sp)
    sw   s0, 4(sp)
    srai t0, a0, 31          # n sign mask (-1 if dividend < 0)
    srai t1, a1, 31          # d sign mask
    xor  s0, t0, t1          # quotient sign mask (survives the call)
    sw   t0, 0(sp)           # save dividend's sign mask (for the remainder)
    xor  a0, a0, t0
    sub  a0, a0, t0          # |dividend|
    xor  a1, a1, t1
    sub  a1, a1, t1          # |divisor|
    call __udivmod
    lw   t0, 0(sp)
    xor  a0, a0, s0
    sub  a0, a0, s0          # apply quotient sign
    xor  a1, a1, t0
    sub  a1, a1, t0          # apply remainder sign (= dividend's)
    lw   s0, 4(sp)
    lw   ra, 8(sp)
    addi sp, sp, 12
    ret

# ---- runtime: print signed decimal + newline ----
__print_int:
    addi sp, sp, -12
    sw   ra, 8(sp)
    sw   s0, 4(sp)
    sw   s1, 0(sp)
    li   a7, 0              # ecall service 0 = putchar (scanf may have left a7=1)
    mv   s0, a0              # value
    bgez s0, __pi_pos
    li   a0, 45             # '-'
    ecall
    sub  s0, zero, s0       # magnitude (INT_MIN stays 0x80000000 -> unsigned 2^31)
__pi_pos:
    li   s1, 0              # digit count
__pi_div:
    mv   a0, s0
    li   a1, 10
    call __udivmod          # a0 = value/10, a1 = value%10
    addi a1, a1, 48         # remainder digit -> ASCII
    addi sp, sp, -4
    sw   a1, 0(sp)          # push digit char
    addi s1, s1, 1
    mv   s0, a0
    bnez s0, __pi_div
__pi_out:
    beqz s1, __pi_done
    lw   a0, 0(sp)
    addi sp, sp, 4
    ecall                   # putchar digit
    addi s1, s1, -1
    j    __pi_out
__pi_done:
    li   a0, 10             # '\n'
    ecall
    lw   s1, 0(sp)
    lw   s0, 4(sp)
    lw   ra, 8(sp)
    addi sp, sp, 12
    ret

