# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function fact(n) ----
fn_fact:
    addi sp, sp, -12
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 12          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer
    sw   a0, -12(s0)          # spill param n (in a0)

    lw   t0, -12(s0)          # read n
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    slt  t0, t1, t0
    xori t0, t0, 1
    push t0
    pop  t0
    beqz t0, __L_else_1
    li   t0, 1
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

    j    __L_endif_2
__L_else_1:
__L_endif_2:
    lw   t0, -12(s0)          # read n
    push t0
    lw   t0, -12(s0)          # read n
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    sub  t0, t0, t1
    push t0
    pop  a0
    call fn_fact
    push a0
    pop  t1
    pop  t0
    mul  t0, t0, t1
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_fact:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- function main() ----
fn_main:
    addi sp, sp, -8
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 8          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    li   t0, 5
    push t0
    pop  a0
    call fn_fact
    push a0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

