# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function main() ----
fn_main:
    addi sp, sp, -16
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 16          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    rdtid t0                 # builtin: this thread's id
    push t0
    pop  t0
    sw   t0, -12(s0)          # init y
    sw   zero, -16(s0)          # init x = 0
    li   t0, 0
    push t0
    pop  t0
    sw   t0, -16(s0)          # assign x
    push t0
    pop  t0
__L_for_top_1:
    lw   t0, -16(s0)          # read x
    push t0
    li   t0, 32
    push t0
    pop  t1
    pop  t0
    slt  t0, t0, t1
    push t0
    pop  t0
    beqz t0, __L_for_end_3
    lw   t0, -12(s0)          # read y
    push t0
    li   t0, 32
    push t0
    pop  t1
    pop  t0
    mul  t0, t0, t1
    push t0
    lw   t0, -16(s0)          # read x
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    lw   t0, -12(s0)          # read y
    push t0
    lw   t0, -16(s0)          # read x
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    li   t0, 4
    push t0
    pop  t1
    pop  t0
    mul  t0, t0, t1
    push t0
    pop  t1
    pop  t0
    setdt t0, t1             # data[index] = value
    li   t0, 0
    push t0
    pop  t0
__L_for_cont_2:
    lw   t0, -16(s0)          # read x
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    pop  t0
    sw   t0, -16(s0)          # assign x
    push t0
    pop  t0
    j    __L_for_top_1
__L_for_end_3:
    li   t0, 0
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

