# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function main() ----
fn_main:
    addi sp, sp, -12
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 12          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    rdtid t0                 # builtin: this thread's id
    push t0
    pop  t0
    sw   t0, -12(s0)          # init i
    lw   t0, -12(s0)          # read i
    push t0
    lw   t0, -12(s0)          # read i
    push t0
    pop  t0
    getdt t0, t0             # t0 = data[index]
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    pop  t1
    pop  t0
    setdt t0, t1             # data[index] = value
    li   t0, 0
    push t0
    pop  t0
    li   t0, 0
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

