# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function main() ----
fn_main:
    addi sp, sp, -40
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 40          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    sw   zero, -32(s0)          # init i = 0
    sw   zero, -36(s0)          # init j = 0
    sw   zero, -40(s0)          # init t = 0
    li   t0, 0
    push t0
    pop  t0
    sw   t0, -32(s0)          # assign i
    push t0
    pop  t0
__L_for_top_1:
    lw   t0, -32(s0)          # read i
    push t0
    li   t0, 5
    push t0
    pop  t1
    pop  t0
    slt  t0, t0, t1
    push t0
    pop  t0
    beqz t0, __L_for_end_3
    lw   t0, -32(s0)          # read i
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    addi t0, s0, -28          # &a
    push t0
    lw   t0, -32(s0)          # read i
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
__L_for_cont_2:
    addi t0, s0, -32          # &i
    push t0
    pop  t1
    lw   t0, 0(t1)           # postfix ++: load old value
    push t0
    addi t0, t0, 1
    sw   t0, 0(t1)           # store stepped value
    pop  t0
    j    __L_for_top_1
__L_for_end_3:
    li   t0, 0
    push t0
    pop  t0
    sw   t0, -32(s0)          # assign i
    push t0
    pop  t0
    li   t0, 4
    push t0
    pop  t0
    sw   t0, -36(s0)          # assign j
    push t0
    pop  t0
__L_while_top_4:
    lw   t0, -32(s0)          # read i
    push t0
    lw   t0, -36(s0)          # read j
    push t0
    pop  t1
    pop  t0
    slt  t0, t0, t1
    push t0
    pop  t0
    beqz t0, __L_while_end_5
    addi t0, s0, -28          # &a
    push t0
    lw   t0, -32(s0)          # read i
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    lw   t0, 0(t1)           # load element
    push t0
    pop  t0
    sw   t0, -40(s0)          # assign t
    push t0
    pop  t0
    addi t0, s0, -28          # &a
    push t0
    lw   t0, -36(s0)          # read j
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    lw   t0, 0(t1)           # load element
    push t0
    addi t0, s0, -28          # &a
    push t0
    lw   t0, -32(s0)          # read i
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    lw   t0, -40(s0)          # read t
    push t0
    addi t0, s0, -28          # &a
    push t0
    lw   t0, -36(s0)          # read j
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    lw   t0, -32(s0)          # read i
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    pop  t0
    sw   t0, -32(s0)          # assign i
    push t0
    pop  t0
    lw   t0, -36(s0)          # read j
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    sub  t0, t0, t1
    push t0
    pop  t0
    sw   t0, -36(s0)          # assign j
    push t0
    pop  t0
    j    __L_while_top_4
__L_while_end_5:
    addi t0, s0, -28          # &a
    push t0
    li   t0, 0
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    lw   t0, 0(t1)           # load element
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

