# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function square(x) ----
fn_square:
    addi sp, sp, -12
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 12          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer
    sw   a0, -12(s0)          # spill param x (in a0)

    lw   t0, -12(s0)          # read x
    push t0
    lw   t0, -12(s0)          # read x
    push t0
    pop  t1
    pop  t0
    mul  t0, t0, t1
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_square:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- function main() ----
fn_main:
    addi sp, sp, -12
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 12          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    li   t0, 42
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    li   t0, -7
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    li   t0, 1
    push t0
    pop  t0
    sw   t0, -12(s0)          # init i
__L_for_top_1:
    lw   t0, -12(s0)          # read i
    push t0
    li   t0, 5
    push t0
    pop  t1
    pop  t0
    slt  t0, t1, t0
    xori t0, t0, 1
    push t0
    pop  t0
    beqz t0, __L_for_end_3
    lw   t0, -12(s0)          # read i
    push t0
    pop  a0
    call fn_square
    push a0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
__L_for_cont_2:
    addi t0, s0, -12          # &i
    push t0
    pop  t1
    lw   t0, 0(t1)           # postfix ++: load old value
    push t0
    addi t0, t0, 1
    sw   t0, 0(t1)           # store stepped value
    pop  t0
    j    __L_for_top_1
__L_for_end_3:
    li   t0, 0
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- runtime: unsigned divmod ----
__udivmod:
    mv   t0, a0              # t0 = dividend
    mv   t1, a1              # t1 = divisor
    bne  t1, zero, __udm_nz
    li   a0, -1
    mv   a1, t0
    ret
__udm_nz:
    li   t2, 0               # quotient
    li   t3, 0               # remainder
    li   t4, 31              # bit index
__udm_loop:
    slli t3, t3, 1
    srl  t5, t0, t4
    andi t5, t5, 1
    or   t3, t3, t5          # r = (r<<1) | bit i of dividend
    bltu t3, t1, __udm_skip
    sub  t3, t3, t1          # r -= divisor
    li   t5, 1
    sll  t5, t5, t4
    or   t2, t2, t5          # set bit i of quotient
__udm_skip:
    addi t4, t4, -1
    bgez t4, __udm_loop
    mv   a0, t2
    mv   a1, t3
    ret

# ---- runtime: print signed decimal + newline ----
__print_int:
    addi sp, sp, -12
    sw   ra, 8(sp)
    sw   s0, 4(sp)
    sw   s1, 0(sp)
    mv   s0, a0              # value
    bgez s0, __pi_pos
    li   a0, 45             # '-'
    ecall
    sub  s0, zero, s0       # magnitude (INT_MIN stays 0x80000000 -> unsigned 2^31)
__pi_pos:
    li   s1, 0              # digit count
__pi_div:
    mv   a0, s0
    li   a1, 10
    call __udivmod          # a0 = value/10, a1 = value%10
    addi a1, a1, 48         # remainder digit -> ASCII
    addi sp, sp, -4
    sw   a1, 0(sp)          # push digit char
    addi s1, s1, 1
    mv   s0, a0
    bnez s0, __pi_div
__pi_out:
    beqz s1, __pi_done
    lw   a0, 0(sp)
    addi sp, sp, 4
    ecall                   # putchar digit
    addi s1, s1, -1
    j    __pi_out
__pi_done:
    li   a0, 10             # '\n'
    ecall
    lw   s1, 0(sp)
    lw   s0, 4(sp)
    lw   ra, 8(sp)
    addi sp, sp, 12
    ret

