# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function fill() ----
fn_fill:
    addi sp, sp, -8
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 8          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    li   t0, 10
    push t0
    la   t0, __g_data          # &data
    push t0
    li   t0, 0
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    li   t0, 20
    push t0
    la   t0, __g_data          # &data
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    li   t0, 30
    push t0
    la   t0, __g_data          # &data
    push t0
    li   t0, 2
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    li   t0, 40
    push t0
    la   t0, __g_data          # &data
    push t0
    li   t0, 3
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    li   t0, 50
    push t0
    la   t0, __g_data          # &data
    push t0
    li   t0, 4
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # store
    push t0
    pop  t0
    li   t0, 0
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_fill:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- function sum_first(n) ----
fn_sum_first:
    addi sp, sp, -20
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 20          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer
    sw   a0, -12(s0)          # spill param n (in a0)

    li   t0, 0
    push t0
    pop  t0
    sw   t0, -16(s0)          # init s
    li   t0, 0
    push t0
    pop  t0
    sw   t0, -20(s0)          # init i
__L_while_top_1:
    lw   t0, -20(s0)          # read i
    push t0
    lw   t0, -12(s0)          # read n
    push t0
    pop  t1
    pop  t0
    slt  t0, t0, t1
    push t0
    pop  t0
    beqz t0, __L_while_end_2
    lw   t0, -16(s0)          # read s
    push t0
    la   t0, __g_data          # &data
    push t0
    lw   t0, -20(s0)          # read i
    push t0
    pop  t1
    pop  t0
    slli t1, t1, 2          # * 4
    add  t0, t0, t1           # &element = base + index*4
    push t0
    pop  t1
    lw   t0, 0(t1)           # load element
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    pop  t0
    sw   t0, -16(s0)          # assign s
    push t0
    pop  t0
    lw   t0, -20(s0)          # read i
    push t0
    li   t0, 1
    push t0
    pop  t1
    pop  t0
    add  t0, t0, t1
    push t0
    pop  t0
    sw   t0, -20(s0)          # assign i
    push t0
    pop  t0
    j    __L_while_top_1
__L_while_end_2:
    lw   t0, -16(s0)          # read s
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_sum_first:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- function main() ----
fn_main:
    addi sp, sp, -8
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 8          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    call fn_fill
    push a0
    pop  t0
    li   t0, 5
    push t0
    pop  a0
    call fn_sum_first
    push a0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- globals ----
__g_data:
    .word 0, 0, 0, 0, 0

