#!/usr/bin/env python3
"""
gen_test_data.py -- generate the data images the testbenches load into
shared_mem's IMG region (IMG_BASE = 0x1000).

Files are written in $readmemb format (one 32-bit binary word per line), the
same format shared_mem.sv's IMG_INIT_FILE expects. shared_mem pre-zeroes the
whole array before $readmemb runs, so a short file leaves the rest at 0 --
deterministic, no X.

The testbenches re-read these same files with their own $readmemb rather than
hardcoding the values, so the expected results are derived from the actual
input instead of a second copy of it that can drift.
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEMS = os.path.join(REPO, "mems")


def write_words(path, words, note):
    lines = [f"// generated by gen_test_data.py -- {note}"]
    lines += [f"{w & 0xFFFFFFFF:032b}" for w in words]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"gen_test_data: {path} ({len(words)} words)")


def main():
    os.makedirs(MEMS, exist_ok=True)

    # test7_kernel: 32 words tiled by 8 lanes x 4 iterations. Values are
    # deliberately not a simple ramp so an off-by-one in the stride shows up
    # as a wrong value rather than a coincidentally-correct neighbour.
    write_words(
        os.path.join(MEMS, "test7_data.mem"),
        [7 * j + 5 for j in range(32)],
        "test7_kernel input: in[j] = 7*j + 5",
    )

    # shared_mem arbitration unit test: 8 distinct, easily-recognisable words
    # so a lane receiving another lane's data is obvious at a glance.
    write_words(
        os.path.join(MEMS, "memtest_data.mem"),
        [0xA0000000 | (i << 16) | (0xBEE0 + i) for i in range(8)],
        "shared_mem arbitration: one distinctive word per lane",
    )

    # An all-zero program, for testbenches that drive shared_mem directly and
    # do not want prog.mem's instruction sitting at word 0.
    write_words(
        os.path.join(MEMS, "zeros.mem"),
        [0],
        "single zero word (inert program image)",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
