# ---- generated by compiler.py (RV32I + M mul) ----
# entry: set up sp, call main, then halt with main's result in a0.
_start:
    li   sp, 65536
    call fn_main
    ebreak

# ---- function main() ----
fn_main:
    addi sp, sp, -16
    mv   t0, s0              # hold caller's frame pointer
    addi s0, sp, 16          # s0 = frame pointer (caller's sp)
    sw   ra, -4(s0)
    sw   t0, -8(s0)          # saved caller's frame pointer

    sw   zero, -12(s0)          # init a = 0
    sw   zero, -16(s0)          # init b = 0
__L_while_top_1:
    li   t0, 1
    push t0
    pop  t0
    beqz t0, __L_while_end_2
    addi sp, sp, -4          # scanf: matched-count slot
    sw   zero, 0(sp)
    call __read_int          # %d
    blez a1, __L_scan_3_fail
    push a0
    addi t0, s0, -12          # &a
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # *arg = value
    lw   t0, 0(sp)
    addi t0, t0, 1
    sw   t0, 0(sp)          # matched++
    lw   t0, 0(sp)          # all directives matched -> count
    j    __L_scan_3_done
__L_scan_3_fail:
    lw   t0, 0(sp)
    bnez t0, __L_scan_3_done
    mv   t0, a1             # nothing matched -> 0 (bad char) or -1 (EOF)
__L_scan_3_done:
    addi sp, sp, 4          # drop the count slot
    push t0
    pop  t0
    lw   t0, -12(s0)          # read a
    push t0
    li   t0, 0
    push t0
    pop  t1
    pop  t0
    sub  t0, t0, t1
    seqz t0, t0
    push t0
    pop  t0
    beqz t0, __L_else_4
    j    __L_while_end_2
    j    __L_endif_5
__L_else_4:
__L_endif_5:
    addi sp, sp, -4          # scanf: matched-count slot
    sw   zero, 0(sp)
    call __read_int          # %d
    blez a1, __L_scan_6_fail
    push a0
    addi t0, s0, -16          # &b
    push t0
    pop  t1
    pop  t0
    sw   t0, 0(t1)           # *arg = value
    lw   t0, 0(sp)
    addi t0, t0, 1
    sw   t0, 0(sp)          # matched++
    lw   t0, 0(sp)          # all directives matched -> count
    j    __L_scan_6_done
__L_scan_6_fail:
    lw   t0, 0(sp)
    bnez t0, __L_scan_6_done
    mv   t0, a1             # nothing matched -> 0 (bad char) or -1 (EOF)
__L_scan_6_done:
    addi sp, sp, 4          # drop the count slot
    push t0
    pop  t0
    lw   t0, -12(s0)          # read a
    push t0
    lw   t0, -16(s0)          # read b
    push t0
    pop  t1
    pop  t0
    mul  t0, t0, t1
    push t0
    pop  t0
    mv   a0, t0
    call __print_int        # magic print: a0 as decimal + newline
    li   t0, 0
    push t0
    pop  t0
    j    __L_while_top_1
__L_while_end_2:
    li   t0, 0
    push t0
    pop  t0
    mv   a0, t0
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

__end_main:
    li   a0, 0               # default return value
    lw   ra, -4(s0)
    mv   sp, s0              # free the frame
    lw   s0, -8(s0)          # restore caller's frame pointer
    ret

# ---- runtime: unsigned divmod ----
__udivmod:
    mv   t0, a0              # t0 = dividend
    mv   t1, a1              # t1 = divisor
    bne  t1, zero, __udm_nz
    li   a0, -1
    mv   a1, t0
    ret
__udm_nz:
    li   t2, 0               # quotient
    li   t3, 0               # remainder
    li   t4, 31              # bit index
__udm_loop:
    slli t3, t3, 1
    srl  t5, t0, t4
    andi t5, t5, 1
    or   t3, t3, t5          # r = (r<<1) | bit i of dividend
    bltu t3, t1, __udm_skip
    sub  t3, t3, t1          # r -= divisor
    li   t5, 1
    sll  t5, t5, t4
    or   t2, t2, t5          # set bit i of quotient
__udm_skip:
    addi t4, t4, -1
    bgez t4, __udm_loop
    mv   a0, t2
    mv   a1, t3
    ret

# ---- runtime: print signed decimal + newline ----
__print_int:
    addi sp, sp, -12
    sw   ra, 8(sp)
    sw   s0, 4(sp)
    sw   s1, 0(sp)
    li   a7, 0              # ecall service 0 = putchar (scanf may have left a7=1)
    mv   s0, a0              # value
    bgez s0, __pi_pos
    li   a0, 45             # '-'
    ecall
    sub  s0, zero, s0       # magnitude (INT_MIN stays 0x80000000 -> unsigned 2^31)
__pi_pos:
    li   s1, 0              # digit count
__pi_div:
    mv   a0, s0
    li   a1, 10
    call __udivmod          # a0 = value/10, a1 = value%10
    addi a1, a1, 48         # remainder digit -> ASCII
    addi sp, sp, -4
    sw   a1, 0(sp)          # push digit char
    addi s1, s1, 1
    mv   s0, a0
    bnez s0, __pi_div
__pi_out:
    beqz s1, __pi_done
    lw   a0, 0(sp)
    addi sp, sp, 4
    ecall                   # putchar digit
    addi s1, s1, -1
    j    __pi_out
__pi_done:
    li   a0, 10             # '\n'
    ecall
    lw   s1, 0(sp)
    lw   s0, 4(sp)
    lw   ra, 8(sp)
    addi sp, sp, 12
    ret

# ---- runtime: buffered one-byte input ----
__getc:
    la   t0, __inq
    lw   a0, 0(t0)
    li   t1, -2
    beq  a0, t1, __getc_fresh   # buffer empty -> read a fresh byte
    sw   t1, 0(t0)              # consume the pushed-back char (mark empty)
    ret
__getc_fresh:
    li   a7, 1                  # ecall service 1 = getchar
    ecall                       # a0 <- next input byte, or -1 at EOF
    ret
__ungetc:
    la   t0, __inq
    sw   a0, 0(t0)             # next __getc returns this char
    ret
__skip_ws:
    addi sp, sp, -4
    sw   ra, 0(sp)
__sw_loop:
    call __getc
    li   t0, -1
    beq  a0, t0, __sw_done      # EOF -> stop (push it back, stays sticky)
    li   t0, 32                 # ' '
    beq  a0, t0, __sw_loop
    addi t0, a0, -9             # tab/nl/vt/ff/cr are 9..13
    li   t1, 4
    bgeu t1, t0, __sw_loop
__sw_done:
    call __ungetc              # restore the first non-whitespace char
    lw   ra, 0(sp)
    addi sp, sp, 4
    ret

# ---- runtime: read a signed/unsigned decimal integer ----
__read_int:
    addi sp, sp, -16
    sw   ra, 12(sp)
    sw   s0, 8(sp)
    sw   s1, 4(sp)
    sw   s2, 0(sp)
    li   s0, 0              # accumulator
    li   s1, 0              # sign flag (1 = negative)
    li   s2, 0              # digit count
__ri_ws:
    call __getc
    li   t0, -1
    beq  a0, t0, __ri_eof
    li   t0, 32
    beq  a0, t0, __ri_ws
    addi t0, a0, -9
    li   t1, 4
    bgeu t1, t0, __ri_ws    # 9..13 are whitespace
    li   t0, 43             # '+'
    beq  a0, t0, __ri_next
    li   t0, 45             # '-'
    bne  a0, t0, __ri_loop
    li   s1, 1
__ri_next:
    call __getc            # first char after the sign
__ri_loop:
    li   t0, 48            # '0'
    blt  a0, t0, __ri_end
    li   t0, 57            # '9'
    bgt  a0, t0, __ri_end
    slli t0, s0, 3         # accumulator * 10 = *8 + *2
    slli t1, s0, 1
    add  s0, t0, t1
    addi t0, a0, -48       # + this digit
    add  s0, s0, t0
    addi s2, s2, 1
    call __getc
    j    __ri_loop
__ri_end:
    call __ungetc          # push back the non-digit terminator
    beqz s2, __ri_nodig
    beqz s1, __ri_pos
    sub  s0, zero, s0      # apply the sign (mod 2^32)
__ri_pos:
    mv   a0, s0
    li   a1, 1
    j    __ri_ret
__ri_nodig:
    li   a0, 0
    li   a1, 0
    j    __ri_ret
__ri_eof:
    call __ungetc          # push EOF back (a0 == -1) so it stays sticky
    li   a0, 0
    li   a1, -1
__ri_ret:
    lw   s2, 0(sp)
    lw   s1, 4(sp)
    lw   s0, 8(sp)
    lw   ra, 12(sp)
    addi sp, sp, 16
    ret

# ---- globals ----
__inq:
    .word -2        # scanf one-char pushback (-2 = empty)

